# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='batman', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='invalid', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
